;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/separator]
type = custom/text
format = <label>
label = " | "

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-padding = 0 
label = %temperature%
label-warn = %temperature%
ramp-0 = "Temperature"
label-foreground = #ffffff

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state>
ws-icon-0 = 1;%{F#92c7c7}1
ws-icon-1 = 2;%{F#92c7c7}2
ws-icon-2 = 3;%{F#92c7c7}3
ws-icon-3 = 4;%{F#92c7c7}4
ws-icon-4 = 5;%{F#92c7c7}5
ws-icon-5 = 6;%{F#92c7c7}6
ws-icon-6 = 7;%{F#92c7c7}7
ws-icon-7 = 8;%{F#92c7c7}8
ws-icon-8 = 9;%{F#92c7c7}9

label-separator = " | "
label-separator-background = #2b2f37

label-focused =  %icon%  
label-focused-foreground = ${colors.foreground}
label-focused-underline =  #565c64
label-focused-padding = 1
label-focused-background = #2b2f37

label-occupied = %icon%
label-occupied-foreground = #646870
label-occupied-background = #2b2f37
label-occupied-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1
label-empty-background = #2b2f37

label-urgent = %icon%
label-urgent-foreground = #88C0D0
label-urgent-background = #2b2f37
label-urgent-padding = 1

[module/bluetooth]
type = custom/text 
content ="BT" 
content-padding = 1
click-left = sh $HOME/.bin/bluetooth &
content-foreground = #ffffff

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>

label-volume = VOL %percentage%%
label-volume-foreground = #ffffff

label-muted = MUT
label-muted-foreground = #ffffff

use-ui-max = false

click-right = pavucontrol

[module/time]
type = internal/date
interval = 5
format = <label>
format-background = #2b2f37
date = %{F#ffffff}%H:%M %p%{F-}  
time-alt = %{F#ffffff}%a, %d %b %Y%{F-}
label = %date%%time%

[module/memory]
type = internal/memory
interval = 2
format = <label>
format-prefix = "Memory "
format-padding = 1
label = %gb_used%
label-foreground = #ffffff

[module/wlan]
type = internal/network
interface = wlan0
interval = 3.0
format-connected =  <label-connected>
label-connected = "%{A1:sh $HOME/.bin/wifimenu:}Connected %{A}"
label-connected-foreground = #ffffff 
format-disconnected = <label-disconnected>
label-disconnected = "%{A1:sh $HOME/.bin/wifimenu:}Disconnected %{A}"
label-disconnected-foreground = #ffffff

[module/ethernet]
type = internal/network
interface = ${system.network_interface_wired}
format-connected = <label-connected>
format-connected-prefix = "󰈁 "
format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-prefix = "󰈂 "
format-disconnected-padding = 1
label-connected = "%{A1:networkmanager_dmenu &:}%downspeed%|%upspeed%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:}Offline%{A}"

[module/battery]
type = internal/battery
full-at = 100
low-at = 20

battery = BAT0
adapter = ACAD
poll-interval = 5

format-charging = <animation-charging> <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
format-low = <animation-low> <label-low>

labal-standard = "%percantage%% "
label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " FULL "
label-low = "%percentage%% "

animation-charging-0 = "!"
animation-charging-1 = "  "
animation-charging-framerate = 500

animation-low-0 = "LOW"
animation-low-1 = ""
animation-low-framerate = 500
animation-low-foreground = #D35F5D

format-charging-foreground = #ffffff

label-charging-foreground = #ffffff
label-discharging-foreground = #ffffff
label-full-foreground = #ffffff

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU " 
format = <label>
label = %percentage%%
label-foreground = #ffffff

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...

[module/space]
type = custom/text
content = " "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
label-layout-padding = 1
label-layout-foreground = #fff
label-indicator-on = %name%
layout-icon-default = some-icon
layout-icon-0 = ru
layout-icon-1 = us
label-indicator-on-capslock = !
label-indicator-off-capslock =
